/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */

import '@stencil/core';

declare global {
  namespace JSX {
    interface Element {}
    export interface IntrinsicElements {}
  }
  namespace JSXElements {}

  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;
    componentOnReady(done: (ele?: this) => void): void;

    forceUpdate(): void;
  }

  interface HTMLAttributes {}
}


declare global {

  namespace StencilComponents {
    interface ScrollAnimationIcon {
      'color': string;
    }
  }

  interface HTMLScrollAnimationIconElement extends StencilComponents.ScrollAnimationIcon, HTMLStencilElement {}

  var HTMLScrollAnimationIconElement: {
    prototype: HTMLScrollAnimationIconElement;
    new (): HTMLScrollAnimationIconElement;
  };
  interface HTMLElementTagNameMap {
    'scroll-animation-icon': HTMLScrollAnimationIconElement;
  }
  interface ElementTagNameMap {
    'scroll-animation-icon': HTMLScrollAnimationIconElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'scroll-animation-icon': JSXElements.ScrollAnimationIconAttributes;
    }
  }
  namespace JSXElements {
    export interface ScrollAnimationIconAttributes extends HTMLAttributes {
      'color'?: string;
    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }

export declare function defineCustomElements(window: any): void;